import pathlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from typing import Union
import pathlib

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """

    def __init__(self, data_fname: Union[pathlib.Path, str]):
        
        self.data_fname = pathlib.Path(data_fname) 
        if not self.data_fname.exists(): 
            raise ValueError
        self.data = pd.DataFrame()

    def read_data(self):
        """Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        self.data = pd.read_json(self.data_fname)


    def show_age_distrib(self) -> tuple[np.ndarray, np.ndarray]:
        """Calculates and plots the age distribution of the participants.

        Returns
        -------
        hist : np.ndarray
        Number of people in a given bin
        bins : np.ndarray
        Bin edges
            """
        bins = np.arange(0, 101, 10)

        hist, bins,_ = plt.hist(self.data["age"].dropna(), bins=bins, edgecolor='black', color='skyblue')

        plt.title('Distribution of Data in Ranges of 10')
        plt.xlabel('Value Ranges')
        plt.ylabel('Frequency')

        plt.show()

        return (hist,bins)
    
    def is_email_valid(self, email):
        if not isinstance(email, str):
            return False
        
        if email.count('@') != 1:
            return False
        
        local, domain = email.split('@')
        
        if not local or not domain:
            return False
        
        if domain.count('.') < 1 or domain.startswith('.') or domain.endswith('.'):
            return False
            
        return True

    def remove_rows_without_mail(self) -> pd.DataFrame:
        """Checks self.data for rows with invalid emails, and removes them.

        Returns
        -------
        df : pd.DataFrame
        A corrected DataFrame, i.e. the same table but with the erroneous rows removed and
        the (ordinal) index after a reset.
            """
        return self.data[self.data['email'].apply(self.is_email_valid)]
        
    def fill_na_with_mean(self) -> tuple[pd.DataFrame, np.ndarray]:
        """Finds, in the original DataFrame, the subjects that didn't answer
        all questions, and replaces that missing value with the mean of the
        other grades for that student.

        Returns
        -------
        df : pd.DataFrame
        The corrected DataFrame after insertion of the mean grade
        arr : np.ndarray
            Row indices of the students that their new grades were generated
            """
        q_cols = [col for col in self.data.columns if col.startswith('q')]

        has_nan_mask = self.data[q_cols].isnull().any(axis=1)

        corrected_indices = self.data.index[has_nan_mask].to_numpy()

        self.data[q_cols] = self.data[q_cols].apply(lambda row: row.fillna(row.mean()),axis=1)

        return self.data, corrected_indices

    def score_subjects(self, maximal_nans_per_sub: int = 1) -> pd.DataFrame:
        """Calculates the average score of a subject and adds a new "score" column
        with it.

        If the subject has more than "maximal_nans_per_sub" NaN in his grades, the
        score should be NA. Otherwise, the score is simply the mean of the other grades.
        The datatype of score is UInt8, and the floating point raw numbers should be
        rounded down.

        Parameters
        ----------
        maximal_nans_per_sub : int, optional
            Number of allowed NaNs per subject before giving a NA score.

        Returns
        -------
        pd.DataFrame
            A new DF with a new column - "score".
        """
        q_cols = [col for col in self.data.columns if col.startswith('q')]

        missing_count = self.data[q_cols].isna().sum(axis=1)

        average_scores = np.floor(self.data[q_cols].mean(axis=1))

        self.data['score'] = average_scores

        self.data.loc[missing_count > maximal_nans_per_sub, 'score'] = pd.NA #

        self.data['score'] = self.data['score'].astype('UInt8')

        return self.data
    
