
import pathlib
from typing import Union
import json
import numpy as np
import pandas as pd
from typing import Tuple
import matplotlib.pyplot as plt

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """

    def __init__(self, data_fname: Union[pathlib.Path, str]):
        if not isinstance(data_fname, (str, pathlib.Path)):
            raise TypeError("data_fname must be string or pathlib.Path object")
        
        path_obj = pathlib.Path(data_fname)

        if not path_obj.exists():
            raise ValueError(f"The file {data_fname} does not exist.")
        self.data_fname = path_obj

    def read_data(self):

        with open(self.data_fname, "r") as file:
            self.data = pd.DataFrame(json.load(file))
    
    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:

        age_column = pd.to_numeric(self.data["age"], errors='coerce')
        clean_ages = age_column.dropna()
        bins = np.linspace(0, 100, 11)
        hist, bin_edges = np.histogram(clean_ages, bins = bins)
        plt.hist(clean_ages, bins=bins)
        plt.show()

        return hist, bin_edges

    def remove_rows_without_mail(self) -> pd.DataFrame:
    
        def is_valid_email(email):
            if not isinstance(email, str):
                return False
            if email.count('@') != 1:
                return False
            if '.' not in email:
                return False
            if email[0] in ('@', '.') or email[-1] in ('@', '.'):
                return False
            at_index = email.find('@')
            if email[at_index + 1] == '.':
                return False
            return True

        valid_mask = self.data['email'].apply(is_valid_email)
        df_clean = self.data[valid_mask].reset_index(drop=True)
        return df_clean

    def fill_na_with_mean(self) -> Tuple[pd.DataFrame, np.ndarray]:
        df_corrected = self.data.copy()
        q_cols = [col for col in df_corrected.columns if col.startswith('q')]

        for col in q_cols:
            df_corrected[col] = pd.to_numeric(df_corrected[col], errors='coerce')

        rows_with_na = df_corrected[q_cols].isna().any(axis=1)
        corrected_indices = df_corrected.index[rows_with_na].to_numpy()
        
        row_means = df_corrected[q_cols].mean(axis=1)
        
        df_corrected[q_cols] = df_corrected[q_cols].T.fillna(row_means).T
        
        return df_corrected, corrected_indices
    
    def score_subjects(self, maximal_nans_per_sub: int = 1) -> pd.DataFrame:

        df_scored = self.data.copy()

        q_cols = [col for col in df_scored.columns if col.startswith('q')]

        for col in q_cols:
            df_scored[col] = pd.to_numeric(df_scored[col], errors='coerce')

        nan_counts = df_scored[q_cols].isna().sum(axis=1)
        raw_means = df_scored[q_cols].mean(axis=1)
        rounded_means = np.floor(raw_means)
        df_scored['score'] = np.where(nan_counts > maximal_nans_per_sub, np.nan, rounded_means)
        df_scored['score'] = df_scored['score'].astype("UInt8")

        return df_scored
    
    def correlate_gender_age(self) -> pd.DataFrame:
        df = self.data.copy()
        q_cols = [col for col in df.columns if col.startswith('q')]
        
        df['age'] = pd.to_numeric(df['age'], errors='coerce')
        for col in q_cols:
            df[col] = pd.to_numeric(df[col], errors='coerce')
            
        df = df.set_index(['gender', 'age'], append=True)
        age_bool_array = df.index.get_level_values('age') > 40
        age_condition = pd.Series(age_bool_array, index=df.index).rename('age')
        grouped = df[q_cols].groupby([
            df.index.get_level_values('gender'),
            age_condition
        ]).mean()
        
        return grouped