import json
import pathlib
import pandas as pd
import numpy as np
from typing import Tuple, Union
import matplotlib.pyplot as plt

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """
    def __init__(self, data_fname: Union[pathlib.Path, str]):
        self.data_fname = pathlib.Path(data_fname)
        if not self.data_fname.exists():
            raise ValueError(f"File {self.data_fname} doesn't exist.")
        self.data = None  # populated once read_data() is called

    def read_data(self):
        """Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        with open(self.data_fname, "r", encoding="utf-8") as f:
            raw = json.load(f)
        self.data = pd.DataFrame(raw)

        question_cols = [col for col in self.data.columns if col.startswith("q")]
        for col in question_cols:
            self.data[col] = pd.to_numeric(self.data[col], errors="coerce")

# 1. Plot the distribution of ages of the participants. 
# The bins for the histogram should be [0, 10), [10, 20), [20, 30), ..., [90, 100]. 
# The function should return the result.

    def show_age_distrib(self) -> Tuple[np.ndarray, np.ndarray]:
        # Coerce ages to numeric (handles string 'nan'), drop missing values
        ages = pd.to_numeric(self.data['age'], errors="coerce")
        participants = ages.dropna().to_numpy(dtype=float)

        # histogram bins: [0,10), [10,20), ..., [90,100]
        bins = np.arange(0, 110, 10)
        hist, edges = np.histogram(participants, bins=bins)

        # draw the bar plot
        plt.bar(edges[:-1], hist, width=10, align='edge', edgecolor='black')
        plt.xlabel('Age')
        plt.ylabel('Number of participants')
        plt.title('Age distribution')
        plt.show()
        return hist, edges

# 2. Participants without a valid email are useless since we can't contact them. 
# Remove all of the rows with an invalid address and return the new DataFrame.
# A valid email address is one that follows these conditions:
# - Contains exactly one "@" sign, but doesn't start or end with it.
# - Contains a "." sign, but doesn't start or end with it.
# - The letter following the "@" sign (i.e, appears after it) must not be ".".
# You're obviously encouraged to think of other email-defining conditions.

    def remove_rows_without_mail(self) -> pd.DataFrame:
        email = self.data['email'].astype(str) # identify email 
        def is_valid_email(email: str) -> bool: #check if mail meets conditions
            if email.count("@") != 1:
                return False
            if email.startswith("@") or email.endswith("@"):
                return False
            if email.count(".") < 1:
                return False
            if email.startswith(".") or email.endswith("."):
                return False
            at_index = email.index("@")
            if at_index + 1 < len(email) and email[at_index + 1] == ".":
                return False
            return True
        remove_invalid_email = email.apply(is_valid_email) 
        valid_email = remove_invalid_email[remove_invalid_email].index 
        valid_email_df = self.data.loc[valid_email].reset_index(drop=True) 
        return valid_email_df
# 3. Some participants haven't answered all of the question. 
# It was decided that the grade for those missing questions will be the average grade of the other question for that subject. 
# Write a method that works on the original DataFrame (in `self.data`), 
# replaces the missing values with the mean for that subject in the other questions and returns 
# the corrected DataFrame as well as a `np.array` of the indices of the rows that were corrected.

    def fill_na_with_mean(self) -> Tuple[pd.DataFrame, np.ndarray]:
        question_cols = [col for col in self.data.columns if col.startswith('q')]
        missing_values = self.data[question_cols].isna().any(axis=1)
        arr = self.data[missing_values].index.to_numpy()
        col_means = self.data[question_cols].mean()
        self.data[question_cols] = self.data[question_cols].fillna(col_means)
        return self.data, arr
    
# 4. Each participants should receive an integer score for his or her answers, given in a new "score" column you should add. 
# After some deliberation it was decided that if a subject has no grade in two questions or more, the score of that subject will be NA. 
# Write a method that produces this score by averaging the grades of the not-NaN questions in the relevant rows.
   
    def score_subjects(self, maximal_nans_per_sub: int = 1) -> pd.DataFrame:
       df = self.data.copy()
       question_cols = [col for col in self.data.columns if col.startswith('q')]
       nan_counts = self.data[question_cols].isna().sum(axis=1)
       row_means = df[question_cols].mean(axis=1)
       floored_means = np.floor(row_means)
       df['score'] = floored_means
       too_many_missing = nan_counts > maximal_nans_per_sub
       df.loc[too_many_missing, 'score'] = np.nan
       df['score'] = df['score'].astype('UInt8')
       return df
    
# 5. **BONUS 15 POINTS** There's reason to believe that there's a correlation between the subject's gender, age and grades.

    def correlate_gender_age(self) -> pd.DataFrame:
        """Looks for a correlation between the gender of the subject, their age
        and the score for all five questions.

        Returns
        -------
        pd.DataFrame
            A DataFrame with a MultiIndex containing the gender and whether the subject is above
            40 years of age, and the average score in each of the five questions.
        """
        df = self.data.copy()
        
        # Ensure age is numeric so we can evaluate if it is > 40 without raising an error
        df['age'] = pd.to_numeric(df['age'], errors='coerce')
        df = df.dropna(subset=['age'])
        df['age_above_40'] = df['age'] > 40
        
        # Group by gender and whether age is above 40
        question_cols = [col for col in df.columns if col.startswith('q')]
        result = df.groupby(['gender', 'age_above_40'])[question_cols].mean()
        
        # Rename the resulting index levels to match the expected output
        result.index.names = ['gender', 'age']
        
        return result
